workspace:
  base: /data/apps/opt
  path: webim-h5


pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - node_modules
      - tag
    volumes:
      - /data/apps/opt/webim-h5:/cache

  build:
    image: node:7.8
    privileged: true
    commands:
      - cd sdk && npm link && cd ..
      - cd webrtc && npm link && cd ..
      - cd emedia && npm link && cd ..
      - npm link easemob-websdk
      - npm link easemob-webrtc
      - npm link easemob-emedia
      - cd demo && npm install
      - npm run build
      # 2.0 demo 相关编译操作在demo目录下面
      - cd ..
      - cp -rf demo/build image/docker/webim/webim
      - cp -rf demo/storybook-static image/docker/webim/storybook
      - echo 'build success'
    when:
      branch: [ dev, master ]


  dockerize-sandbox:
      image: plugins/docker
      environment:
        - DOCKER_LAUNCH_DEBUG=true
      debug: true
      repo: docker-registry-cn.easemob.com/kubernetes/im/webim
      #2.0会被drone截断成2
      tags: 20
      registry: docker-registry-cn.easemob.com
      secrets: [ docker_username, docker_password ]
      dockerfile: image/docker/webim/Dockerfile
      context: image/docker/webim/
      when:
        branch: dev

  deploy-sandbox:
    image: docker-registry-cn.easemob.com/kubernetes/im/webim-h5-deploy:latest
    pull: true
    environment:
      - DOCKER_LAUNCH_DEBUG=true
      - TAG=20
    secrets: [ ssh_key, jumpserver_host, jumpserver_port, sandbox_host ]
    debug: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: dev

  dockerize-online:
    image: plugins/docker
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    debug: true
    repo: docker-registry-cn.easemob.com/kubernetes/im/webim
    tags: ${DRONE_COMMIT:0:7}
    registry: docker-registry-cn.easemob.com
    secrets: [ docker_username, docker_password ]
    dockerfile: image/docker/webim/Dockerfile
    context: image/docker/webim/
    when:
      branch: master

  deploy-online:
    image: docker-registry-cn.easemob.com/kubernetes/im/webim-h5-online:latest
    pull: true
    environment:
      - DOCKER_LAUNCH_DEBUG=true
      - TAG=${DRONE_COMMIT:0:7}
    secrets: [ ssh_key, jumpserver_host, jumpserver_port, online_host ]
    debug: true
    volumes:
      - /data/tag/webim-h5:/data/tag/webim-h5
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master

  rollback-online:
    image: docker-registry-cn.easemob.com/kubernetes/im/webim-h5-rollback:latest
    pull: true
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [ ssh_key, jumpserver_host, jumpserver_port, online_host ]
    debug: true
    volumes:
      - /data/tag/webim-h5:/data/tag/webim-h5
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: rollback

  rebuild-cache:
      image: drillster/drone-volume-cache
      rebuild: true
      mount:
        - node_modules
        - tag
      volumes:
        - /data/apps/opt/webim-h5:/cache

  notify:
    image: drillster/drone-email
    port: 25
    secrets: [ plugin_host, plugin_from, plugin_username, plugin_password ]
    when:
      status:  [ failure, success ]